---
# install gitolite (most tasks executed as sudo git, one as sudo root)

- name: sudo test
  shell: echo $HOME

# fix to [ansible issue #7474]:https://github.com/ansible/ansible/issues/7474 that fails the gitoline clone process and prints the message: "github.com has an unknown hostkey"
# the fix was suggested by @eveyrat on [protobox issue #78]:https://github.com/protobox/protobox/issues/78
- name: add github key to known hosts
  shell: ssh-keyscan github.com >> /etc/ssh/ssh_known_hosts
  sudo_user: root

- name: clone gitolite repo
  git: repo=git://github.com/sitaramc/gitolite dest={{ gitolite_dir }}

- name: make bin dir
  file: path=~/bin state=directory owner=git group=git

- name: install gitolite
  shell: "{{ gitolite_dir }}/install -to ~/bin"

- name: generate ssh key for gitolite admin
  local_action: command creates=gitolite_admin_key ssh-keygen -f gitolite_admin_key -N ""
  sudo: no

- name: copy public gitolite admin key
  copy: src=gitolite_admin_key.pub dest=/dev/shm/gitolite_admin_key.pub

- name: gitolite setup
  shell: ~/bin/gitolite setup -pk /dev/shm/gitolite_admin_key.pub

- name: fix gitolite update hook for HTTP access
  lineinfile: "dest={{ git_home }}/bin/lib/Gitolite/Hooks/Update.pm state=present
  regexp='^BEGIN { exit 0'
  insertafter='^#!/usr/bin/perl'
  line='BEGIN { exit 0 if exists $ENV{GL_BYPASS_UPDATE_HOOK}; }'"
  tags:
    - hookfix

### redmine_git_hosting specific stuff

- name: install ruby for redmine_git_hosting hook
  apt: pkg=ruby state=present
  sudo_user: root

- name: allow config options for redmine_git_hosting hooks
  lineinfile: name={{ git_home }}/.gitolite.rc state=present
    regexp="GIT_CONFIG_KEYS"
    line="    GIT_CONFIG_KEYS                 =>  '.*',"

- name: copy patched post-receive hook for redmine_git_hosting
  template: src=post-receive.j2 dest={{ git_home }}/.gitolite/hooks/common/post-receive


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
